# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0002_auto_20170911_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ispublished',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='lastedited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
