# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0004_auto_20170911_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributers',
            new_name='contributors',
        ),
    ]
