# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0005_auto_20170911_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('attributes', models.ManyToManyField(to='divtags.ProjectAttribute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divtags.Project')),
            ],
        ),
        migrations.AddField(
            model_name='projectattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divtags.ProjectAttributeType'),
        ),
    ]
