# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 14:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0006_auto_20171017_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
