# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0008_auto_20171115_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='versionno',
            field=models.CharField(default=0.1, max_length=20),
            preserve_default=False,
        ),
    ]
