# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0009_projectversion_versionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='iterationno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='versionno',
            field=models.IntegerField(),
        ),
    ]
