# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0010_auto_20171115_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='curriterationno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='currversionno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pubiterationno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pubversionno',
            field=models.IntegerField(null=True),
        ),
    ]
