# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0012_projectversionexperimental'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversionexperimental',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
