# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0013_projectversionexperimental_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectversionexperimental',
            name='parent',
        ),
        migrations.AddField(
            model_name='projectversion',
            name='experimentals',
            field=models.ManyToManyField(to='divtags.ProjectVersionExperimental'),
        ),
    ]
