# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0014_auto_20171120_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currexperimentalno',
            field=models.IntegerField(null=True),
        ),
    ]
