# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0015_project_currexperimentalno'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
