# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0017_auto_20171121_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
