# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0018_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(null=True, upload_to='img/ProjectLogos'),
        ),
    ]
