# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divtags', '0019_auto_20180113_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/ProjectImages')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(to='divtags.ProjectImage'),
        ),
    ]
